Repository dariomrk/EduLink, pull requests merged in 2023-05, with the labels that each got.

#1 Add Mantine dependency to frontend
  frontend/package-lock.json
  frontend/package.json
Labels: chore

#2 Add Branches section to README
  README.md
Labels: documentation

#3 Add bug report form
  github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: documentation

#4 Add backend dependencies
  backend/Api/Api.csproj
  backend/Application/Application.csproj
  backend/Data/Data.csproj
  backend/backend.sln
Labels: chore

#5 Add backend continuous integration
  .github/workflows/backend-build-test.yml
Labels: chore

#7 Add Excalidraw database schema file
  DatabaseSchema.excalidraw
Labels: documentation

#8 Move ISSUE_TEMPLATE to .github
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: chore

#9 Add Models to backend Data layer
  backend/Data/Enums/Currency.cs
  backend/Data/Interfaces/IEduLinkModel.cs
  backend/Data/Models/Appointment.cs
  backend/Data/Models/AvailableTimeSpan.cs
  backend/Data/Models/BaseModel.cs
  backend/Data/Models/City.cs
  backend/Data/Models/Country.cs
  backend/Data/Models/Field.cs
  backend/Data/Models/LoginTimestamp.cs
  backend/Data/Models/Message.cs
  backend/Data/Models/PasswordHashingAlgorithm.cs
  backend/Data/Models/Region.cs
  backend/Data/Models/StudentsReview.cs
  backend/Data/Models/Subject.cs
  backend/Data/Models/TutoringPost.cs
  backend/Data/Models/TutoringPostAvailability.cs
  backend/Data/Models/TutoringPostField.cs
  backend/Data/Models/TutorsReview.cs
  backend/Data/Models/User.cs
Labels: enhancement

#14 Update backend workflow
  .github/workflows/backend-build-test.yml
Labels: chore

#16 Remove Id property from model
  backend/Data/Models/LoginTimestamp.cs
Labels: fix

#17 Update excalidraw database schema
  DatabaseSchema.excalidraw
Labels: documentation

#13 Configure database context
  DatabaseSchema.excalidraw
  backend/.editorconfig
  backend/.env.example
  backend/.gitignore
  backend/Api/Api.csproj
  backend/Api/Api.csproj.user
  backend/Api/Program.cs
  backend/Api/Properties/launchSettings.json
  backend/Api/appsettings.Development.json
  backend/Api/appsettings.Production.json
  backend/Api/appsettings.json
  backend/Data/Constants/RawSql.cs
  backend/Data/Context/ConfigurationHelper.cs
  backend/Data/Context/EduLinkDbContext.cs
  backend/Data/Context/EduLinkDbContextFactory.cs
  backend/Data/Data.csproj
  backend/Data/Enums/FileType.cs
  backend/Data/Migrations/20230511125034_Initial.Designer.cs
  backend/Data/Migrations/20230511125034_Initial.cs
  backend/Data/Migrations/EduLinkDbContextModelSnapshot.cs
  backend/Data/Models/Appointment.cs
  backend/Data/Models/AvailableTimeSpan.cs
  backend/Data/Models/City.cs
  backend/Data/Models/Country.cs
  backend/Data/Models/Field.cs
  backend/Data/Models/File.cs
  backend/Data/Models/LoginTimestamp.cs
  backend/Data/Models/Message.cs
  backend/Data/Models/PasswordHashingAlgorithm.cs
  backend/Data/Models/Region.cs
  backend/Data/Models/StudentsReview.cs
  backend/Data/Models/Subject.cs
  backend/Data/Models/TutoringPost.cs
  backend/Data/Models/TutoringPostAvailability.cs
  backend/Data/Models/TutoringPostField.cs
  backend/Data/Models/TutorsReview.cs
  backend/Data/Models/User.cs
  backend/backend.sln
  backend/docker-compose.yml
Labels: enhancement

#18 Adjust workflow triggers
  .github/workflows/backend-build-test.yml
Labels: chore

#20 Add backend local setup section to README
  README.md
Labels: documentation

#21 Add backend prerequisites to README
  README.md
Labels: documentation

#11 Add generic repository implementation to backend Data layer
  backend/Data/Enums/RepositoryActionResult.cs
  backend/Data/Interfaces/IEduLinkModel.cs
  backend/Data/Interfaces/IRepository.cs
  backend/Data/Repositories/BaseRepository.cs
Labels: enhancement

#29 Clean up Program.cs
  backend/Api/Program.cs
Labels: enhancement

#34 Add React Router dependency.
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement

#35 Hide internal IUserService methods
  backend/Application/Interfaces/IUserService.cs
Labels: fix

#42 Add TODO to Issue action
  .github/workflows/todo-to-issue-manual.yml
  .github/workflows/todo-to-issue.yml
  README.md
  backend/Api/Program.cs
  backend/Application/Dtos/User/Mappings.cs
  backend/Application/Extensions/TutoringPostExtensions.cs
  backend/Application/Extensions/UserExtensions.cs
  backend/Application/Services/TutoringPostService.cs
  backend/Data/Models/Appointment.cs
  backend/Data/Models/User.cs
Labels: enhancement

#53 Adjust todo to issue action trigger
  .github/workflows/todo-to-issue.yml
Labels: chore, enhancement

#49 Add footer
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/Footer/index.js
  frontend/src/fonts/dm-sans.ttf
  frontend/src/fonts/fonts.css
  frontend/src/img/Facebook.svg
  frontend/src/img/Instagram.svg
  frontend/src/img/Linkedin.svg
  frontend/src/img/Youtube.svg
  frontend/src/img/logo.svg
  frontend/src/index.css
  frontend/src/index.jsx
  frontend/src/style/colors.js
  frontend/vite.config.js
  package-lock.json
Labels: feature, frontend

#76 Resolve circular dependency
  backend/Application/Interfaces/IAppointmentService.cs
  backend/Application/Interfaces/ITutoringPostService.cs
  backend/Application/Services/AppointmentService.cs
  backend/Application/Services/TutoringPostService.cs
  backend/Application/Validators/CreateAppointmentRequestValidator.cs
Labels: fix, backend

#78 Implement FieldService
  backend/Application/Interfaces/IFieldService.cs
  backend/Application/Services/FieldService.cs
Labels: feature, backend

#77 Register services and repositories for DI
  backend/Api/Program.cs
  backend/Application/Services/IdentityService.cs
  backend/Data/Repositories/BaseRepository.cs
Labels: feature, backend

#75 add button
  frontend/.eslintrc.cjs
  frontend/src/App.jsx
  frontend/src/components/CustomButton/CustomButton.jsx
  frontend/src/components/CustomButton/index.js
Labels: feature, frontend

#89 Remove package-lock from root.
  package-lock.json
Labels: chore, fix

#92 Fix total tutoring hours query
  backend/Application/Dtos/User/Mappings.cs
  backend/Application/Services/AppointmentService.cs
Labels: fix, backend

#94 Implement LocationController
  backend/Api/Controllers/LocationsController.cs
  backend/Api/Endpoints.cs
  backend/Application/Dtos/Location/CityIdResponseDto.cs
  backend/Application/Dtos/Location/CityResponseDto.cs
  backend/Application/Dtos/Location/Mappings.cs
  backend/Application/Dtos/Location/RegionIdResponseDto.cs
  backend/Application/Dtos/Location/RegionResponseDto.cs
  backend/Application/Interfaces/ILocationService.cs
  backend/Application/Services/LocationService.cs
Labels: feature, backend

#107 Set cors
  backend/Api/Program.cs
Labels: chore, backend

#104 add not found page
  frontend/src/img/wrong.svg
  frontend/src/pages/NotFoundPage/NotFoundPage.jsx
  frontend/src/pages/NotFoundPage/index.js
  frontend/src/router/Router.jsx
Labels: feature, frontend

#111 Sort by distance
  backend/Application/Dtos/Common/SortRequestDto.cs
  backend/Application/Extensions/AppointmentExtensions.cs
  backend/Application/Extensions/MessageExtensions.cs
  backend/Application/Extensions/TutoringPostExtensions.cs
  backend/Application/Extensions/UserExtensions.cs
  backend/Application/Services/UserService.cs
Labels: backend, enhancement

#110 Add GetTutoringPostFromSubject
  backend/Api/Controllers/PostsController.cs
  backend/Api/Endpoints.cs
  backend/Application/Interfaces/ITutoringPostService.cs
  backend/Application/Services/TutoringPostService.cs
Labels: feature, backend

#112 Fix routes
  backend/Api/Endpoints.cs
  backend/Application/Services/LocationService.cs
Labels: fix, backend

#113 Get all posts from a country
  backend/Api/Controllers/PostsController.cs
  backend/Api/Endpoints.cs
  backend/Application/Interfaces/ITutoringPostService.cs
  backend/Application/Services/TutoringPostService.cs
Labels: backend, enhancement

#109 Add apiService and tokenService
  frontend/config.json
  frontend/src/.vscode/settings.json
  frontend/src/services/apiService.js
  frontend/src/services/tokenService.js
Labels: feature, frontend

#121 Add subjects controller
  backend/Api/Controllers/SubjectsController.cs
  backend/Api/Endpoints.cs
  backend/Application/Dtos/Subject/SubjectResponseDto.cs
  backend/Application/Interfaces/ISubjectService.cs
  backend/Application/Services/SubjectService.cs
Labels: feature, backend

#125 Refactored Post service and controller
  backend/Api/Controllers/PostsController.cs
  backend/Api/Endpoints.cs
  backend/Application/Interfaces/ITutoringPostService.cs
  backend/Application/Services/TutoringPostService.cs
Labels: backend, enhancement
